### ISSUE TITLE
[Bug] Uploading the same photo two times and not stopping the upload after already uploade

### ISSUE THREAD

**Issue by Thewisem** [stingle/stingle-photos-android#79] opened 2021-02-17 17:40 UTC
I upload the same photo on the cloud twice and it gets uploaded twice. I would like for you to implement a system where a photo cannot be uploaded twice.

**Comment by alexamiryan** [comment] 2021-02-17 19:50
Duplicate of #73

**Closed** 2022-09-05 02:04 UTC
Labels: duplicate
